// Generated by CoffeeScript 2.7.0
(function() {
  var assert, assign, validator, warn;

  ({assert} = require('chai'));

  assign = require('../assign-variable.js');

  validator = null;

  warn = null;

  assign.onWarning(function(msg) {
    return warn = msg;
  });

  beforeEach(function() {
    return warn = null;
  });

  describe('assign tests', function() {
    it('should return undefined when no arguments are given', function() {
      return assert.equal(assign(), void 0);
    });
    it('should ignore alt value because it is undefined', function() {
      return assert.equal(assign('', void 0), '');
    });
    it('should ignore alt value because it is of same type', function() {
      return assert.equal(assign('', '?'), '');
    });
    it("should return the alt type when values' type doesn't match alts' type", function() {
      return assert.equal(assign('', 0), 0);
    });
    it("should generate correct warninging message", function() {
      assign(void 0, 0, 'test');
      return assert.deepEqual(warn, {
        sender: "assign-variable",
        text: "type mismatch",
        id: "test",
        type: "warn",
        value: void 0
      });
    });
    return it("should generate correct warninging message", function() {
      assign('0', 0, 'test');
      return assert.deepEqual(warn, {
        sender: "assign-variable",
        text: "type mismatch",
        id: "test",
        type: "warn",
        value: '0'
      });
    });
  });

}).call(this);
